name: Hello World Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2
      
      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install pytest
          pip install pylint

      # Run echo command
      - name: Run Echo
        run: echo "Hello, world!"

      # Set PYTHONPATH to include the root directory
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      # Run test
      - name: Run test
        run: pytest test/  # Ensure your test files are in a 'test/' directory

      # Lint code
      - name: Lint Code
        run: pylint app.py test/*.py  # Replace with your main Python files

      # Set up Docker Buildx (for multi-platform builds if needed)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build project
      - name: Build Project
        run: docker build .
